name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ghcr.io/mnofresno/random-games:0.0.1
        labels: |
          org.opencontainers.image.source=${{ github.repository }}

    - name: Deploy to Server
      env:
        AUTODEPLOY_URL: ${{ vars.AUTODEPLOY_URL }}
        KEY_FILE_FOR_DEPLOY: ${{ secrets.KEY_FILE_FOR_DEPLOY }}
      run: |
          response=$(curl -X POST \
              -H "Content-Type: application/json" \
              -d '{
                  "repo": "random-games",
                  "key": "'"${KEY_FILE_FOR_DEPLOY}"'",
                  "run_in_background": true,
                  "commit": {
                      "sha": "'"${{ github.sha }}"'",
                      "author": "'"${{ github.actor }}"'"
                  }
                  }' \
              -s -o response_body.txt -w "%{http_code}" \
              --fail \
              "https://${AUTODEPLOY_URL}?repo=random-games&key=${KEY_FILE_FOR_DEPLOY}&create_repo_if_not_exists=true"
          cat response_body.tx
          if [ "$response" -ge 400 ]; then
              echo "Request failed with status code $response"
              exit 1
          fi
